[build]
publish = "site/"

# Install deps and build the site
command = """
pip install -r requirements.txt &&
mkdocs build
"""

[build.environment]
# Latest python version supported in netlify at time of adding
PYTHON_VERSION = "3.8"
